export const USERREGISTER_SUCCESS = 'USERREGISTER_SUCCESS';
export const USERREGISTER_FAIL = 'USSERREGISTER_FAIL';
export const USERLOGIN_SUCCESS = 'USERLOGIN_SUCCESS';
export const USERLOGIN_FAIL = 'USERLOGIN_FAIL';